---
name: Test

on:
  push:
    branches:
      - test_aws

env:
  NODE_VERSION: 18

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Verify NodeJS installation
        run: |
          node -v
      - name: Build Docker Image
        working-directory: src
        run: |
          docker build -t apix:latest .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check AWS Authentication
        run: |
          aws sts get-caller-identity

