---
name: CI
on:
  pull_request:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pyton
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'