---
name: Test

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Verify NodeJS installation
        run: |
          node -v
      - name: Build Docker Image
        working-directory: src
        run: |
          docker build -t apix:latest .
          
      

